name: TAIPO BIST - AUTO

on:
  schedule:
    # 10:00–10:10 TR => 07:00–07:10 UTC (her dakika)
    - cron: "0-10 7 * * *"

    # 11:10–17:10 TR => 08:10–14:10 UTC
    - cron: "10 8 * * *"
    - cron: "10 9 * * *"
    - cron: "10 10 * * *"
    - cron: "10 11 * * *"
    - cron: "10 12 * * *"
    - cron: "10 13 * * *"
    - cron: "10 14 * * *"

  workflow_dispatch:

jobs:
  run-auto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AUTO
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MODE: AUTO
        run: python main.py
